### ISSUE TITLE
What should be done with linebreaks/softbreaks in Slate transform?

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#100]
I'm unclear that this is what should be happening?
https://github.com/accordproject/markdown-transform/blob/90cf0cfa38582e9a38029573ad7fddba8470f32c/packages/markdown-slate/src/ToSlateVisitor.js#L228-L241

**Comment by dselman** [comment]
Interesting thread on this, including when to use <br/>
https://github.com/ckeditor/ckeditor5/issues/4542

**Comment by jeromesimeon** [comment]
Note on this thread:
- Line breaks are two spaces followed by a new line within a paragraph
```
This is a line break  
with something after it
```
- Softbreaks are just a new line
```
This is a softbreak
With something after it
```

In Dingus:
<img width="1378" alt="Screenshot 2019-11-07 at 2 01 14 PM" src="https://user-images.githubusercontent.com/670099/68418847-155e9200-0167-11ea-9556-7bcef2599095.png">

**Comment by dselman** [comment]
Resolved: linebreaks and soft breaks are both represented as inlines in the Slate DOM.
