### ISSUE TITLE
Markus Dingus!

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#111]
**Is your feature request related to a problem? Please describe.**
It's a feature request related to a feature. The idea would be to have a deployed _Dingus_ in the style of https://spec.commonmark.org/dingus/ but for CiceroMark.

**Describe the solution you'd like**
It could be almost exactly like the commonmark dingus but:
1. Left box lets you write CiceroMark
2. Right box shows:
   - Preview
   - HTML
   - CommonMark DOM
   - CiceroMark Dom
   - Slate DOM

**Comment by adrijshikhar** [comment]
i would like to work on this issue.

**Comment by jeromesimeon** [comment]
> i would like to work on this issue.

That would be great! I'll assign it.

**Comment by jeromesimeon** [comment]
Since we switched the parser to `markdown-it` this feature should probably be based on: https://markdown-it.github.io

**Comment by irmerk** [comment]
@adrijshikhar I'm marking this as open.

**Comment by jeromesimeon** [comment]
Declaring this issue done. A fully functional "dingus" is available at https://templatemark-dingus.netlify.app
