### ISSUE TITLE
Link Title Skip if Null

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-transform#117]
**Describe the bug**
A test in `markdown-editor` is failing around the way a link is round-tripped.

```bash
FAIL  src/SlateAsInputEditor/index.test.js
  ● SlateAsInputEditor component › successful roundtrip

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -1,8 +1,8 @@
      My Heading

    - This is text. This is *italic* text. This is **bold** text. This is a [link](https://clause.io). This is `inline code`.
    + This is text. This is *italic* text. This is **bold** text. This is a [link](https://clause.io ""). This is `inline code`.
```
This stems from [this code](https://github.com/accordproject/markdown-transform/blob/master/packages/markdown-slate/src/ToSlateVisitor.js#L246), where the `title` is set to `""` if null.

**Expected behavior**
Probably need to skip this behavior entirely.

**Additional context**
[This commit](https://github.com/accordproject/markdown-transform/commit/e1ed1c9cfc333fbbf4baf61c9e79a01abfb58b46)

**Comment by jeromesimeon** [comment]
@irmerk I can't find a failing test. Do you know how to reproduce this? Or has it been fixed already?

**Comment by irmerk** [comment]
I should have provided this context, but I commented out the test in `markdown-editor` with this PR: https://github.com/accordproject/markdown-editor/pull/183

See [this code](https://github.com/accordproject/markdown-editor/blob/master/src/SlateAsInputEditor/index.test.js#L58-L64)

**Comment by jeromesimeon** [comment]
I would not consider this a bug. Links with no titles are treated as links with empty titles. This is consistent with CommonMark spec and parser. e.g., See example in the Dingus.

<img width="1372" alt="Screenshot 2019-11-11 at 3 29 32 PM" src="https://user-images.githubusercontent.com/670099/68618806-2d505180-0498-11ea-8f89-42f088e15c8b.png">

Note that the kind of test pointed to in the `markdown-editor` link above are often likely to fail. Rountripping from markdown text back to an identical markdown text is not a property that `markdown-transform` is trying to achieve.

(A typical example is if: you would try to roundtrip `this is *italics*` and `this is _italics_` you would obtain only get `this is *italics*` as a result)

**Comment by jeromesimeon** [comment]
I would close this issue as "not valid". @irmerk let me know if that makes sense and if any other questions.
