### ISSUE TITLE
DOCX -> CiceroMark

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-transform#144]
It would be useful to be able to create contracts from existing MS Word DOCX files.

https://github.com/mwilliamson/mammoth.js#readme
https://pandoc.org

This should be integrated with #145

**Comment by jeromesimeon** [comment]
@dselman Can we consider this issue closed in #153 ?

**Comment by dselman** [comment]
Superseded by: https://github.com/accordproject/markdown-transform/issues/247
