### ISSUE TITLE
Template Grammar to Slate DOM with Wrapped Variables

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-transform#151]
**Is your feature request related to a problem? Please describe.**
Need a way to go from a template `grammar` or `sample` to a Slate DOM with `wrapVariables: true` 

**Describe the solution you'd like**
This will allow for rendering a formatted clause template without necessarily having the `clauseTemplate`

**Comment by jeromesimeon** [comment]
A good chunk of work for this has been done in the development branch. The approach is as follows:
-[x] define a DOM for the grammar (it is called `templatemark`)
-[x] create a parser for the grammar and transform to template mark
-[ ] add a translation from `templatemark` to `slate` DOM (TODO)

**Comment by dselman** [comment]
@jeromesimeon can this be closed?

**Comment by jeromesimeon** [comment]
I always interpreted this issue as encompassing `grammar -> Slate` transform as well. Which is technically still open. We could close this issue which isn't entirely clear and open a new one. @irmerk ?

**Comment by irmerk** [comment]
Unsure, it sounds like it though? I'm not clear on if going from a template `grammar` or `sample` to a Slate DOM with `wrapVariables: true` is possible now.

**Comment by jeromesimeon** [comment]
`wrapVariables: true` does not exist anymore. But:
- going from `sample` to Slate DOM does exist.
- Going from `grammar` to Slate DOM does not exist (but would be needed if we want to do "design mode").

**Comment by irmerk** [comment]
Happy to close this, but am not sure I understand the requirement enough to make a refined/updated issue. @jeromesimeon would you mind?

**Comment by jeromesimeon** [comment]
> Happy to close this, but am not sure I understand the requirement enough to make a refined/updated issue. @jeromesimeon would you mind?

hm. It would be useful to have at least a discussion about "design mode". Will we do it or not and if yes in which form.

**Comment by jeromesimeon** [comment]
Closing this, replaced by newer #338
