### ISSUE TITLE
Defense for Transforms

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-transform#160]
We should provide protections for the transform to handle more robust markdown transforms.

For instance, putting `cicero-ui`'s `README.md` file through the transform fails at [this point](https://github.com/accordproject/markdown-transform/blob/master/packages/markdown-slate/src/ToSlateVisitor.js#L264).

**Comment by jeromesimeon** [comment]
> For instance, putting `cicero-ui`'s `README.md` file through the transform fails at [this point](https://github.com/accordproject/markdown-transform/blob/master/packages/markdown-slate/src/ToSlateVisitor.js#L264).

This should not fail at this point anymore, handling links properly in release 0.9.9. It _may_ fail at some other point in the editor, I haven't checked yet.

**Comment by jeromesimeon** [comment]
Cicero UI `README.md` now works in the Markdown Editor:

<img width="714" alt="Screenshot 2020-02-12 at 9 47 45 AM" src="https://user-images.githubusercontent.com/670099/74347279-dd2aa900-4d7e-11ea-95b5-dbb71d8dff40.png">

**Comment by irinbanerjee** [comment]
hi ! can I be assigned this?

**Comment by irmerk** [comment]
Hello @irinbanerjee! We are actually migrating this repository (as well as `markdown-editor` and `cicero-ui`) to a new version of Slate, so this should probably hold off until we are done with that. It is being tracked [here](https://github.com/accordproject/markdown-editor/issues/297).

**Comment by irmerk** [comment]
@irinbanerjee:

accordproject/cicero-ui#357 and accordproject/markdown-editor#297 have been finished, so there is no longer a blocker on this issue. The migration _may_ have solved this issue, so look into that first.

**Comment by jeromesimeon** [comment]
meh
