### ISSUE TITLE
quote or block quote, that is the question

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#174]
**Describe the bug**
Both `quote` and `block_quote` are handled in part of the Slate transform code. They both seem to really mean to support commonmark block quotes, and possibly `quote` is obsolete.

- it is supported in the slate to CiceroMark transform here: https://github.com/accordproject/markdown-transform/blob/2b2764ebf25cc24aefd81fcdd26baff9495590ef/packages/markdown-slate/src/slateToCiceroMarkDom.js#L111
- it is not supported in the CiceroMark to slate transform
- it is mentioned in the markdown editor here: https://github.com/accordproject/markdown-editor/blob/6c17020a5d7408d0a167d80a6a76fdae5cdfbd7f/src/schema.js#L7
but I don't think anywhere else

**Comment by jeromesimeon** [comment]
This issue could use input from @DianaLease and @irmerk

**Comment by DianaLease** [comment]
hmm, `quote` does not seem necessary. Looks to me like it could safely be removed.

**Comment by jeromesimeon** [comment]
Removed in `markdown-transform` PR #172 

Will leave open until it's removed from `markdown-editor`
