### ISSUE TITLE
Support Slate 0.50.x

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-transform#175]
The `SlateTransformer` currently wraps the JSON in a Slate `Value`. In Slate 0.50.x `Value` has been removed and Slate operates on JS objects.

**Describe the solution you'd like**
Modify the codebase such that it can support both 0.46.x and 0.50.x usage.

**Comment by jeromesimeon** [comment]
> The `SlateTransformer` currently wraps the JSON in a Slate `Value`. In Slate 0.50.x `Value` has been removed and Slate operates on JS objects.
> 
> **Describe the solution you'd like**
> Modify the codebase such that it can support both 0.46.x and 0.50.x usage.

I remember thinking it would be nice to remove slate entirely from the current code of the `markdown-transform` and let the `markdown-editor` be the one responsible for doing the conversion to Slate object (for `0.46.x`). That would remove one dependency.

@dselman for `0.50.x` is there a description of the JSON for Slate anywhere?

**Comment by irmerk** [comment]
The issue https://github.com/accordproject/cicero-ui/issues/282 could potentially be helped by support of `v0.50.x`

**Comment by jeromesimeon** [comment]
> The issue [accordproject/cicero-ui#282](https://github.com/accordproject/cicero-ui/issues/282) could potentially be helped by support of `v0.50.x`

Looking at Cicero UI #282 I don't see the connection. Could you elaborate?

**Comment by irmerk** [comment]
This is what Diana and I had spoken about where we are at an impasse, and upgrading to `v0.50` could potentially help that. This was just for reference between the two issues.

**Comment by jeromesimeon** [comment]
> This is what Diana and I had spoken about where we are at an impasse, and upgrading to `v0.50` could potentially help that. This was just for reference between the two issues.

That doesn't help very much. There is nothing in #282 which mentions being at an impasse or anything related to Slate 0.50?

**Comment by jeromesimeon** [comment]
> The `SlateTransformer` currently wraps the JSON in a Slate `Value`. In Slate 0.50.x `Value` has been removed and Slate operates on JS objects.
> 
> **Describe the solution you'd like**
> Modify the codebase such that it can support both 0.46.x and 0.50.x usage.

The removal of the slate dependency and corresponding `Value` calls has been removed in #181 and #182. This means the `markdown-slate` transform never relies on the Slate DOM and only uses the JSON representation.

_warning_ I do not believe this means we support Slate 0.50.x. As far as I can tell the JSON representation has changed as well. e.g., I think `nodes` as been renamed to `children` https://docs.slatejs.org/concepts/02-nodes

Flag for @DianaLease

**Comment by DianaLease** [comment]
> > The `SlateTransformer` currently wraps the JSON in a Slate `Value`. In Slate 0.50.x `Value` has been removed and Slate operates on JS objects.
> > **Describe the solution you'd like**
> > Modify the codebase such that it can support both 0.46.x and 0.50.x usage.
> 
> The removal of the slate dependency and corresponding `Value` calls has been removed in #181 and #182. This means the `markdown-slate` transform never relies on the Slate DOM and only uses the JSON representation.
> 
> _warning_ I do not believe this means we support Slate 0.50.x. As far as I can tell the JSON representation has changed as well. e.g., I think `nodes` as been renamed to `children` https://docs.slatejs.org/concepts/02-nodes
> 
> Flag for @DianaLease

That's fine for now. What we'll need to think about when we update to slate 0.50.x is if we'll want to stay backwards compatible with 0.47.x.

**Comment by jeromesimeon** [comment]
> That's fine for now. What we'll need to think about when we update to slate 0.50.x is if we'll want to stay backwards compatible with 0.47.x.

👍 agreed. Also this will have to be tested live on a parallel version of the markdown editor.

**Comment by jeromesimeon** [comment]
Also, possibly useful typescript interfaces for Slate 0.50.x
https://github.com/ianstormtaylor/slate/tree/master/packages/slate/src/interfaces

**Comment by DianaLease** [comment]
Text nodes are differen in 0.50.x vs 0.47.x. ---

**Text node in 0.47.x:**
```
  {
    object: 'text',
    text: 'Hello!',
    marks: []
  }
```

**Simple text node in 0.50.x:**
```
  {
    text: "Hello!"
  }
```

Text nodes too can contain any custom properties you want, and that's how you implement custom formatting like bold, italic, code, etc. (https://docs.slatejs.org/concepts/02-nodes#text)
**Text node in 0.50.x with formatting:**
```
  {
    text: 'A string of bold text',
    bold: true,
  }
```

**Comment by jeromesimeon** [comment]
> Text nodes are differen in 0.50.x vs 0.47.x. ---
> 
> **Text node in 0.47.x:**
> 
> ```
>   {
>     object: 'text',
>     text: 'Hello!',
>     marks: []
>   }
> ```
> 
> **Simple text node in 0.50.x:**
> 
> ```
>   {
>     text: "Hello!"
>   }
> ```
> 
> Text nodes too can contain any custom properties you want, and that's how you implement custom formatting like bold, italic, code, etc. (https://docs.slatejs.org/concepts/02-nodes#text)
> **Text node in 0.50.x with formatting:**
> 
> ```
>   {
>     text: 'A string of bold text',
>     bold: true,
>   }
> ```

Hi @DianaLease I think it does mean we _could_ keep it as the current format if we wanted to (and maybe clean up later) am I misunderstanding?

**Comment by jeromesimeon** [comment]
Concretely: `object` and `mark` were built-into 0.40 but now they would just become part of our custom properties.
