### ISSUE TITLE
AP Documentation Sync

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-transform#18]
## Tasks
- Create charter file
- Ensure layout and structure of README is consistent with other AP repos

## Related Issues:
- [Cicero UI Issue 65](https://github.com/accordproject/cicero-ui/issues/65)

**Comment by RanadeepPolavarapu** [comment]
I can take this one.

**Comment by irmerk** [comment]
We'll still want the Accord Project logo centered in the README.

**Comment by mbtamuli** [comment]
@irmerk Since this is part of open issue and is currently unassigned, is anything remaining for the docs from the list that you created above.

I can see some have been fixed in https://github.com/accordproject/ergo/pull/688

**Comment by irmerk** [comment]
Actually no, I'll close this issue.
