### ISSUE TITLE
Mono-Repo Documentation

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-transform#19]
## Tasks
- Ensure the main `README` captures the overall structure of the monorepo
- Ensure layout and structure of `README` is consistent with other AP repos
- Relevant information:
  - Markdown Transform
    - CommonmarkParser converts markdown text to an instance of the CommonMark AST
    - CommonmarkToString converts an AST to a markdown string
  - Slate Markdown Transform
    - The Cicero DOM extends [this](https://models.accordproject.org/commonmark/markdown.html)
    - Adds `Clause`, `Variable`, and `ComputedVariable` as `Child` nodes

## Related Issues:
- [Cicero UI Issue 65](https://github.com/accordproject/cicero-ui/issues/65)

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by christyjacob4** [comment]
Hey @irmerk Please assign me to this

**Comment by jeromesimeon** [comment]
I would add to this: make sure `README` and/or `DEVELOPPERS` clearly document now to build with lerna. (See also discussion in PR #69 reported by @dlemstra ).

Currently: `README` does not mention lerna bootstrapping, and `DEVELOPPERS` wrongly points to `npm install`.

**Comment by irmerk** [comment]
@christyjacob4 moving this back to being an open issue.

**Comment by jeromesimeon** [comment]
The `README` documents the structure of the mono-repo and how to build using `lerna`.
