### ISSUE TITLE
CiceroMark variables inside HTML blocks rather than HTML inlines are not detected

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#197]
**Describe the bug**
Variables corresponding to HTML inlines are detected:
```
bash-3.2$ markus parse --sample test/data/variable.md --cicero
3:05:08 PM - info:
{
  "$class": "org.accordproject.commonmark.Document",
  "xmlns": "http://commonmark.org/xml/1.0",
  "nodes": [
    {
      "$class": "org.accordproject.commonmark.Paragraph",
      "nodes": [
        {
          "$class": "org.accordproject.commonmark.Text",
          "text": "This is a "
        }, 
        {
          "$class": "org.accordproject.ciceromark.Variable",
          "id": "shipper",
          "value": ""Party A""
        }, 
        {
          "$class": "org.accordproject.commonmark.Text",
          "text": " property."
        }
      ]
    }
  ]
}
bash-3.2$ more test/data/variable-start.md 
<variable id="shipper" value="%22Party%20A%22"/> <foo/>
bash-3.2$ markus parse --sample test/data/variable-start.md --cicero
3:05:26 PM - info:
{
  "$class": "org.accordproject.commonmark.Document",
  "xmlns": "http://commonmark.org/xml/1.0",
  "nodes": [
    {
      "$class": "org.accordproject.commonmark.Paragraph",
      "nodes": [
        {
          "$class": "org.accordproject.ciceromark.Variable",
          "id": "shipper",
          "value": ""Party A""
        }, 
        {
          "$class": "org.accordproject.commonmark.Text",
          "text": " "
        }, 
        {
          "$class": "org.accordproject.commonmark.HtmlInline",
          "tag": {
            "$class": "org.accordproject.commonmark.TagInfo",
            "tagName": "foo",
            "attributeString": "",
            "attributes": [],
            "content": "",
            "closed": true
          },
          "text": "<foo/>"
        }
      ]
    }
  ]
}
```
But variables making an HTML blocks aren't:
```
bash-3.2$ more test/data/variable-block.md 
<variable id="shipper" value="%22Party%20A%22"/>
Still an HTML block
bash-3.2$ markus parse --sample test/data/variable-block.md --cicero
3:06:22 PM - info:
{
  "$class": "org.accordproject.commonmark.Document",
  "xmlns": "http://commonmark.org/xml/1.0",
  "nodes": [
    {
      "$class": "org.accordproject.commonmark.HtmlBlock",
      "tag": {
        "$class": "org.accordproject.commonmark.TagInfo",
        "tagName": "variable",
        "attributeString": "id = "shipper" value = "%22Party%20A%22" ",
        "attributes": [
          {
            "$class": "org.accordproject.commonmark.Attribute",
            "name": "id",
            "value": "shipper"
          }, 
          {
            "$class": "org.accordproject.commonmark.Attribute",
            "name": "value",
            "value": "%22Party%20A%22"
          }
        ],
        "content": "",
        "closed": false
      },
      "text": "<variable id="shipper" value="%22Party%20A%22"/>
Still an HTML block"
    }
  ]
}
```

**Flags**
This is either a bug or a feature request, depending on your interpretation.

**Comment by jeromesimeon** [comment]
The corresponding specification for HTML blocks is here: https://spec.commonmark.org/0.29/#html-blocks

The relevant part of that specification is:
> 7. Start condition: line begins with a complete open tag (with any tag name other than script, style, or pre) or a complete closing tag, followed only by whitespace or the end of the line.
End condition: line is followed by a blank line.

**Comment by jerrybuks** [comment]
I would love to give this a try?

**Comment by jeromesimeon** [comment]
@jerrybuks sounds great! This is a pretty high priority one, let me know if you need help / have any questions.

**Comment by jeromesimeon** [comment]
A couple of snapshots using the CommonMark dingus, to illustrate the root of the problem:

![InlineOrBlock](https://user-images.githubusercontent.com/670099/76662071-59b5d080-6553-11ea-8782-cd3a3804d8a5.gif)

![MoreHTMLBlockWeirdness](https://user-images.githubusercontent.com/670099/76662085-66d2bf80-6553-11ea-88f0-05c25a1f9bb3.gif)

**Comment by jeromesimeon** [comment]
@jerrybuks A couple of quick pointers.

- The CommonMark dingus is a good way to get a sense for what's happening in the markdown parsing phase (the markdown transform always starts there, then transforms further into CiceroMark)
- I had in mind that the right place to fix this would be in the CommonMark -> CiceroMark transform located in the `./packages/markdown-cicero` part of the project. -- but it's just a thought.

**Comment by jerrybuks** [comment]
> @jerrybuks A couple of quick pointers.
> 
> * The [CommonMark dingus](https://spec.commonmark.org/dingus/) is a good way to get a sense for what's happening in the markdown parsing phase (the markdown transform always starts there, then transforms further into CiceroMark)
> * I had in mind that the right place to fix this would be in the CommonMark -> CiceroMark transform located in the `./packages/markdown-cicero` part of the project. -- but it's just a thought.

Okay, I will take a look at it. Thanks for the pointers

**Comment by jerrybuks** [comment]
@Jerome, Just observed that this is the default commonMark behaviour as pointed out [here](https://stackoverflow.com/questions/29368902/how-can-i-wrap-my-markdown-in-an-html-div). when  keep an empty line in between the HTML block and the markdown code, the contents will be parsed as Markdown. I tried this out for both cases( when an empty line is kept and when its not). When the empty line is there, the parsing worked fine and when its not, that's when the parsing doesn't work fine. here are some screenshots.
For this screen shot, I transformed to CiceroMarkDom, then to html and then back to markdown, everthing worked fine(while having the emtpy line)
![Screenshot from 2020-03-20 17-39-14](https://user-images.githubusercontent.com/39066907/77185507-cdb32400-6ad1-11ea-98c7-8e2bcb275d1f.png)
![Screenshot from 2020-03-20 17-29-07](https://user-images.githubusercontent.com/39066907/77185192-4a91ce00-6ad1-11ea-926a-360cd309086a.png)

while for this one, I didn't observe the emtpy line and it broke.
![Screenshot from 2020-03-20 17-26-40](https://user-images.githubusercontent.com/39066907/77185618-fe935900-6ad1-11ea-8a53-51754b3bdc58.png)

**Comment by jeromesimeon** [comment]
> @jerome, Just observed that this is the default commonMark behaviour as pointed out [here](https://stackoverflow.com/questions/29368902/how-can-i-wrap-my-markdown-in-an-html-div). when keeping an empty line in-between the HTML block and the markdown code, the contents will be parsed as Markdown. I tried this out for both cases( when an empty line is kept and when its not). When the empty line is there, the parsing worked fine and when its not, that's when the parsing doesn't work fine. here are some screenshots.
> For this screen shot, I transformed to CiceroMarkDom, then to html and then back to markdown, everthing worked fine(while having the emtpy line)
> ![Screenshot from 2020-03-20 17-39-14](https://user-images.githubusercontent.com/39066907/77185507-cdb32400-6ad1-11ea-98c7-8e2bcb275d1f.png)
> ![Screenshot from 2020-03-20 17-29-07](https://user-images.githubusercontent.com/39066907/77185192-4a91ce00-6ad1-11ea-926a-360cd309086a.png)
> 
> while for this one, I didn't observe the emtpy line and it broke.
> ![Screenshot from 2020-03-20 17-26-40](https://user-images.githubusercontent.com/39066907/77185618-fe935900-6ad1-11ea-8a53-51754b3bdc58.png)

Yes I think what's happening here (following the commonmark spec) is that if you put an extra new lines, the following content is a paragraph (i.e., not _inside_ the code block). So you have two code blocks with a paragraph in between. Those two code blocks are unrelated so I'm not sure how this helps -- common mark will not tell us that we have proper open/closing of those tags, etc.

I think the question really is: what behaviour do we want for HTML blocks. I'm not sure we've really decided.

**Comment by jerrybuks** [comment]
> Yes I think what's happening here (following the commonmark spec) is that if you put an extra new lines, the following content is a paragraph (i.e., not _inside_ the code block). So you have two code blocks with a paragraph in between. Those two code blocks are unrelated so I'm not sure how this helps -- common mark will not tell us that we have proper open/closing of those tags, etc.
> 
> I think the question really is: what behaviour do we want for HTML blocks. I'm not sure we've really decided.

ooh, I think I get now, so the solution to probably to improve  commonMark's parsing of markdown to able to handle the block element, just like it handles inline?

**Comment by jerrybuks** [comment]
> I think the question really is: what behaviour do we want for HTML blocks. I'm not sure we've really decided.
@jeromesimeon should I still proceed in fixing these, as described in this Issue(#197)

**Comment by jerrybuks** [comment]
@jeromesimeon can I still work on this, was a bit confused, if I should still work on this, based on your reply "I think the question really is: what behaviour do we want for HTML blocks. I'm not sure we've really decided.".....

**Comment by jeromesimeon** [comment]
> @jeromesimeon can I still work on this, was a bit confused, if I should still work on this, based on your reply "I think the question really is: what behaviour do we want for HTML blocks. I'm not sure we've really decided.".....

Sure! Sorry if my comment was confusing, what I was trying to say is that a first step in addressing this issue is to decide what behaviour we want? Should this kind of variable be: an error? handled as if it was an inline?

I think it would be great if at least users writing templates with things like:
```
This is an name:

{{name}}

```
Against a sample:
```
This is a name:

"Jerry"
```

Which generate:
```
This is a name:

<variable id="name" value="Jerry"/>
```

Would either get notified that this is not supported (not sure at which point of the process) or be allowed to use it and it's working as expected.

Does that make some sense?

**Comment by jerrybuks** [comment]
> > @jeromesimeon can I still work on this, was a bit confused, if I should still work on this, based on your reply "I think the question really is: what behaviour do we want for HTML blocks. I'm not sure we've really decided.".....
> 
> Sure! Sorry if my comment was confusing, what I was trying to say is that a first step in addressing this issue is to decide what behaviour we want? Should this kind of variable be: an error? handled as if it was an inline?
> 
> I think it would be great if at least users writing templates with things like:
> 
> ```
> This is a name:
> 
> {{name}}
> ```
> 
> Against a sample:
> 
> ```
> This is a name:
> 
> "Jerry"
> ```
> 
> Which generates:
> 
> ```
> This is a name:
> 
> <variable id="name" value="Jerry"/>
> ```
> 
> Would either get notified that this is not supported (not sure at which point of the process) or be allowed to use it and it's working as expected.
> 
> Does that make some sense?

Yeah, makes more sense now, considering the options you gave (supporting or returning an "unsupported notification"), not sure which is a better option, but allowing the support introduces more flexibility, on the other restricting it  and sending an unsupported notification helps keep and preserve a particular standard. But I think handling it as inline and perhaps specifying this in the docs is a better option, what do you think?

**Comment by jeromesimeon** [comment]
> Yeah, makes more sense now, considering the options you gave (supporting or returning an "unsupported notification"), not sure which is a better option, but allowing the support introduces more flexibility, on the other restricting it and sending an unsupported notification helps keep and preserve a particular standard. But I think handling it as inline and perhaps specifying this in the docs is a better option, what do you think?

Right. So yes definitely if we could find a way to naturally support it, that would be my preference. (With the old principle of "least astonishment" for our users).

The reason I'm unclear about it is that I don't know how easy/hard it is, and I don't have a clear idea in my mind about whether we can cover all cases.

So: yes help on this would be amazing!

**Comment by jerrybuks** [comment]
> > Yeah, makes more sense now, considering the options you gave (supporting or returning an "unsupported notification"), not sure which is a better option, but allowing the support introduces more flexibility, on the other restricting it and sending an unsupported notification helps keep and preserve a particular standard. But I think handling it as inline and perhaps specifying this in the docs is a better option, what do you think?
> 
> Right. So yes definitely if we could find a way to naturally support it, that would be my preference. (With the old principle of "least astonishment" for our users).
> 
> The reason I'm unclear about it is that I don't know how easy/hard it is, and I don't have a clear idea in my mind about whether we can cover all cases.
> 
> So: yes help on this would be amazing!

Okay, great, will give it a try!

**Comment by jeromesimeon** [comment]
This problem is fixed on the development branch, which now parses variables in the template grammar using a proper markdown extension (using `markdown-it`).
