### ISSUE TITLE
Release Notes (v0.20 Project)

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-transform#20]
## Tasks
- This will track and construct the overall release notes for this repo in relation to the `v0.20` project
  - Will cover everything from the inception of this repo

## Related Issues:
- N/A

**Comment by irmerk** [comment]
# Current Information:

This library utilizes the official Accord Project version of Concerto (`@accordproject/concerto`)

## The project structure:
- **`markdown-common`**: Transformation between Commonmark strings and a Commonmark AST
- **`markdown-cicero`**: Additional transformation between CommonMark AST and an extension for Accord Project's Cicero
- **`markdown-slate`**: Additional transformation between CommonMark AST and a Slate DOM
- **`markdown-cli`**: Top-level command line interface for the transformation libraries

## Miscellaneous information:
- Clauses are recognised through the info part of the code block
- Calculation exists for convenience for clause text without variables tags

## API

Most API calls return pure JSON rather than Concerto objects, for portability.

Classes are `CommonMark` and `CiceroMark` containing operations to/from string and to/from CommonMark

## CLI 

#### Options:
> All examples are using `mdtransform parse --sample test/ul.md`, which prints the CommonMark AST by usin the CommonMark parser and transformer

- `--noIndex`: Disable automatic indexing for ordered lists.

Here is an example of roundtrip for an ordered list with and without the `--noIndex` option:
```
bash-3.2$ mdtransform parse --sample ol-tight.md --roundtrip 
09:37:47 - info: 
This is an ordered list:

1. one
2. two
3. three

Done.
bash-3.2$ mdtransform parse --sample ol-tight.md --roundtrip --noIndex 
09:37:50 - info: 
This is an ordered list:

1. one
1. two
1. three

Done.
```

- `--roundtrip`: Re-generates the markdown from the AST

- `--cicero`: Print the CiceroMark AST

- `--slate`: Displays the Slate DOM

**Comment by irmerk** [comment]
Note that `--roundtrip` and `--generateMarkdown` are similar and could use review.

**Comment by jeromesimeon** [comment]
There should not be a `--generateMarkdown` anymore

**Comment by jeromesimeon** [comment]
@irmerk We have now a regular release process for this, with release notes. This is already used in the `0.20` release. Can we close?
