### ISSUE TITLE
CLI changes: wrapVariables and noQuote options

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-transform#211]
This is a proposal to make some changes in how we describe wrapVariables and noQuote, and the CLI that drives them.

## wrapVariables

The intention of the transformation option to wrap or unwrap variables is to provide a format that is easier for the Cicero-UI editor to deal with, in that model information for variables (type and formatting information, values for conditional variables) has been moved from the model for the template, inline into the mark-up.

I therefore propose that we define a *new* format, called *CiceroEdit* for this explicit purpose. I think this has several benefits:

- IMO it is clearer what the intention is, and we can provide more complex transformations from `CiceroMark <-> CiceroEdit`, rather than dealing with this using options.

- It is more future proof, as *CiceroEdit* is likely to evolve significantly as we add new capabilities to the editor. For example, when we implement pop-ups for `enums`, we will have to inline the enum values. Having a **name** for this format will help communication.

- The name is intended to signify that this is **not** intended to be a long-lived persistence format, but rather is a transient format used during the scope of a relatively short-lived editing session.

## CLI Commands and noQuote

The `noQuote` options (which removes `"` and `{{` from CiceroMark, rendering it unparseable, is a lossy transformation. I therefore propose that this become an output format in its own right in the CLI, and that we simply refer to it as `--format markdown` rather than as a drafting option. It is then conceptually a peer of the plain text transformation, which should also become an output format.

So markus CLI becomes more like:

```
markus transform --input <file> --from <input-format>  --to <output-format> --output <path to the output file>
```

Formats:
1. markdown
1. commonmark
1. plaintext
1. ciceromark
1. ciceroedit
1. pdf
1. docx 
1. contractdata
1. html
1. slate

Examples

```
markus transform --input sample.md --from commonmark --to ciceromark --output output.md
markus transform --input sample.md --from ciceromark --to plaintext --output output.txt
markus transform --input sample.md --from ciceromark --to ciceroedit --output edit.md
markus transform --input sample.md --from ciceromark --to markdown --output unparseable.md
markus transform --input sample.html --from html --to pdf --output output.pdf
markus transform --input data.json --from json --to pdf --output output.pdf
markus transform --input sample.md --from ciceromark --to contractdata --output data.json
markus transform --input sample.md --from commonmark --to contractdata --output data.json // fails!
markus transform --input sample.md --from markdown --to contractdata --output data.json // fails!
markus transform --input sample.pdf --from pdf --to contractdata --output data.json // fails!
```

The CLI would be updated to automatically calculate the shortest path from the input format to the output format, based on the transformations available, hiding the existing options from the user. This should make the CLI much more future proof, as we add new transformations, and prevent an explosion in the number of format specific options. I think it can also clean the code up significantly and make it more maintainable.

> Do we want to auto-detect the input and output format based on file name extension?

The `draft` and `parse` CLI options would be removed, as they are superseded by the more general `transform` command, which treats JSON as a valid input and output format via the `contractdata` format.

## Proposed States and Transitions

![transformations](https://user-images.githubusercontent.com/623108/78967477-803b3d00-7afa-11ea-8b4b-4b2e3a12567e.png)

For example, the diagram shows that it is possible to convert from HTML to markdown, but not (currently) possible to convert from Slate to DOCX.

**Comment by jeromesimeon** [comment]
Yes I think it's really great! I had not thought of making the wrapped variables variant a different format. To me that makes a lot of sense.

I also like `--input` to replace the distinction between `draft --data` and `parse --sample`.

I am a bit more confused about making a format distinction between:
```
This is "John"
```
and
```
This is John
```

This isn't very clearly a different format both of which are perfectly valid markdown -- Also whether one is markdown or now is a factor of the template grammar (which we don't have access to at this point).

**Comment by jeromesimeon** [comment]
One more question. What happens to the DOM v text representation in this proposal.

**Comment by dselman** [comment]
Good questions. I will explore both with some test code...

**Comment by jeromesimeon** [comment]
@dselman Can we close this? (maybe open a separate issue on ciceroEdit?)

**Comment by jeromesimeon** [comment]
@dselman Can we consider this issue resolved? The status in the new release:

- noQuotes can be obtained through a transform to the `ciceromark_unquote` format
- "wrapped variables" correspond to the new **and deprecated** format `ciceroedit`

**Comment by jeromesimeon** [comment]
Closing. Feel free to re-open if you disagree.
