### ISSUE TITLE
Make decorators on variables available within CiceroMark

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-transform#249]
It would be very useful for transformations to have access to all the decorators placed on variable Concerto types -- allowing them to customise the output based on metadata specified on the variable types.

For example, this could be used by signature blocks to ensure that variables with the `@SignatureVariable()` decoration are rendered as white text in PDF, and are not editable in the Slate editor.

See: https://github.com/accordproject/cicero/issues/557

```
/**
 * A Signature block
 */
asset SignatureClause extends AccordClause {

  @SignatureVariable()
  --> AccordParty party

  @DocuSignTab("Text")
  @SignatureVariable()
  o String favoriteColor

  @DocuSignTab("Title", "optional")
  @SignatureVariable()
  o String title

  @DocuSignTab("SignHere")
  @SignatureVariable()
  o String signature

  @DocuSignTab("FullName")
  @SignatureVariable()
  o String name

  @DocuSignTab("DateSigned")
  @SignatureVariable()
  o String date
}
```

**Describe the solution you'd like**
All decorators on a Concerto type to be copied into the typed CiceroMark variable node.

**Describe alternatives you've considered**
None.

**Additional context**

To access decorators:

```
const val = myField.getDecorators();
```

**Comment by jeromesimeon** [comment]
ouch... I completely forgot about this. I think this will have to happen in a future release.

**Comment by dselman** [comment]
Implemented.
