### ISSUE TITLE
Transform from markdown to PDF fails when image link exists in markdown.

### ISSUE THREAD

**Issue by martinhalford** [accordproject/markdown-transform#260]
**Describe the bug**
Transform command throws an unhandled exception when transforming from markdown to pdf if image link contained within markdown document.

**To Reproduce**
1. Include an image link within markdown document. For example...
```
![logo](https://s3-ap-southeast-2.amazonaws.com/images.benext.io/beNext_orange-darkgreen-sig-870x225.png "")
```
2. Execute transform command. For example...
```
markus transform --input sample.md --to pdf --output output.pdf
```
3. See error
```
(node:66215) UnhandledPromiseRejectionWarning: Invalid image: Error: ENOENT: no such file or directory, open 'https://s3-ap-southeast-2.amazonaws.com/images.benext.io/beNext_orange-darkgreen-sig-870x225.png'
Images dictionary should contain dataURL entries (or local file paths in node.js)
(node:66215) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Expected behavior**
The image URL is valid markdown syntax. Ideally would expect PDF to be generated with the image rendered inside the PDF document. Alternatively, would expect graceful handling of image links if not supported.

**Comment by jeromesimeon** [comment]
I'm unclear if we want to support external links for images. @dselman @DianaLease any opinion?

**Comment by martinhalford** [comment]
@dselman  @jeromesimeon  @DianaLease 

If external links for images are not to be supported for `markdown-pdf` then the only way to include images within a contract that uses `markdown-pdf` is via embedded images.

This is fine if images are static (such as logos etc.) which can be embedded within the `grammar.tem.md` but not so easy for dynamic images that form part of the contract data. 

Like many contract signing platforms (e.g. like DocuSign), we are embedding signature images into the contract instance in order to provide reasonable evidence that the contract has been legally signed and therefore is legally enforceable (along with some metadata and selfie images).

In order to do this, images must form part of the `data.json` payload, which is fine if the `data.json` is passed as a file argument to the CLI.

However, when using `Cicero Server`, the `data.json` must be passed to the API as part of the HTTP POST request. 

Unfortunately, even with one (1) small base64 encoded PNG image embedded, the HTTP POST request payload becomes too large.

Current workaround is to use `markdown-html` which supports both linked and embedded images.

![image](https://user-images.githubusercontent.com/970336/91651481-aa54c200-ead0-11ea-8413-29373a7f0474.png)

![image](https://user-images.githubusercontent.com/970336/91651496-cbb5ae00-ead0-11ea-9875-6ef5c745eafa.png)

![image](https://user-images.githubusercontent.com/970336/91651513-fb64b600-ead0-11ea-8f6c-e3089c2b2de1.png)

**Comment by dselman** [comment]
Implemented.
