### ISSUE TITLE
Download CommonMark and CiceroMark models from their published version

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#27]
CTO models for CommonMark DOM and CiceroMark DOM are copied in the code here:
https://github.com/accordproject/markdown-transform/blob/master/packages/markdown-common/src/Models.js
and here:
https://github.com/accordproject/markdown-transform/blob/master/packages/markdown-cicero/src/Models.js

Those should be consistent with the officially published version at https://models.accordproject.org

Instead of copying those in the code (which is error prone and does not guarantee consistency when the published version changes), we should download them from the https://models.accordproject.org as part of the build process.

This could be done through the new concerto command line (see https://github.com/accordproject/concerto/issues/67)

**Comment by jeromesimeon** [comment]
It might be a good idea to rename the `markdown.cto` model to `commonmark.cto`, see https://github.com/accordproject/models/issues/51
and in the README in this project.

**Comment by hritikgupta** [comment]
Hi @jeromesimeon, I would like to work on this issue. Please assign it to me.

**Comment by jeromesimeon** [comment]
@hritikgupta I'm afraid I have to move this issue forward for the coming release, so I'm reassigning it to myself. Apologies if you had already started working on it.

**Comment by jeromesimeon** [comment]
Completed and merged in #89
