### ISSUE TITLE
Whitespace removed near {{#ulist}} element

### ISSUE THREAD

**Issue by martinhalford** [accordproject/markdown-transform#289]
**Describe the bug**
Whitespace near {{#ulist}} in `grammar.tem.md` is removed when `sample.md` generated.

**To Reproduce**
Consider the following `grammar`.
```
**COMMISSION**

The commission (including GST) is based on the following:

{{#ulist commissions}}
Sale price: $ {{salePrice as "0,0"}}; Commission: $ {{commissionAmount as "0,0"}} 
{{/ulist}}
```

This is rendered as:
```
**COMMISSION**

The commission (including GST) is based on the following:
-  Sale price: $ 1,650,000; Commission: $ 130,000
-  Sale price: $ 150,000; Commission: $ 75,000
-  Sale price: $ 1,000,000; Commission: $ 25,000
-  Sale price: $ 500,000; Commission: $ 5,000
```
The extra CRLF between the plain text "The commission..." and the `{{#ulist}}` is removed.

Attempts to **force** the extra line with double spaces (`"  "`), newline (`"/n"`) and (`"\"`) failed.

> Note: There generally seems to be an issue with the way whitespace is handled in CiceroMark.  It's often necessary to use `"\"` or `"/n"` to force newlines.

**Expected behaviour**
```
**COMMISSION**

The commission (including GST) is based on the following:

-  Sale price: $ 1,650,000; Commission: $ 130,000
-  Sale price: $ 150,000; Commission: $ 75,000
-  Sale price: $ 1,000,000; Commission: $ 25,000
-  Sale price: $ 500,000; Commission: $ 5,000
```

**Additional context**
Cicero version 0.21.3

**Comment by jeromesimeon** [comment]
The parser/drafter engine does not attempt to preserve non-significant (in the sense of that the difference you show here will not make any difference on the rendered document) whitespace. What's your usecase?

**Comment by jeromesimeon** [comment]
To explain what I mean by that whitespace (those newlines) aren't significant. You can see that the rendering does not change whether you have new lines or not.

![ListWhitespace](https://user-images.githubusercontent.com/670099/90399410-e4ea4380-e068-11ea-9abf-badb716be319.gif)

**Comment by martinhalford** [comment]
Looks like this is "by design" so closing this issue.
