### ISSUE TITLE
CLI is broken (missing some dependencies?)

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#29]
**Describe the bug**
Installing the Command Line Interface works:
```
bash-3.2$ npm -g install @accordproject/markdown-cli 
+ @accordproject/markdown-cli@0.3.2
updated 1 package in 10.988s
```

But trying to run it, you get:
```
bash-3.2$ mdtransform --help
module.js:550
    throw err;
    ^

Error: Cannot find module 'jsome'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jeromesimeon/.nvm/versions/node/v8.12.0/lib/node_modules/@accordproject/markdown-cli/node_modules/@accordproject/markdown-common/lib/Logger.js:1214:39)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Most likely some dependencies are missing from the `package.json` in `markdown-cli`.

**Comment by KL13NT** [comment]
Is anyone on this? I'd love to give it a shot as my first PR!

**Comment by irmerk** [comment]
> Is anyone on this? I'd love to give it a shot as my first PR!

All yours!

**Comment by KL13NT** [comment]
So, it seems that `jsome` is added to the `devDependencies` of 'markdown-common' package that uses it in `Logger.js` instead of `dependencies`, so when installing without the `--dev` flag the package is not actually installed:

![image](https://user-images.githubusercontent.com/20807178/65895925-78147f00-e3ac-11e9-8197-556a85c29fd9.png)

I'd like confirmation for this though as I'm unable to build the package locally. Should I open a PR for this?

**Comment by irmerk** [comment]
@KL13NT does that solve the mini-issue then? @jeromesimeon and @dselman would know more about this repo.

**Comment by jeromesimeon** [comment]
> So, it seems that `jsome` is added to the `devDependencies` of 'markdown-common' package that uses it in `Logger.js` instead of `dependencies`, so when installing without the `--dev` flag the package is not actually installed:
> 
> ![image](https://user-images.githubusercontent.com/20807178/65895925-78147f00-e3ac-11e9-8197-556a85c29fd9.png)
> 

That sounds right.

> I'd like confirmation for this though as I'm unable to build the package locally. Should I open a PR for this?
> 

Could you clarify this comment? If you are having trouble installing the `markdown-transform` package locally, we would certainly welcome a new issue on that.

> EDIT: Running `yarn add jsome` after running `yarn add @accordproject/markdown-cli` solves this:
> 
> ![image](https://user-images.githubusercontent.com/20807178/65896292-3afcbc80-e3ad-11e9-80ac-7e85718529c3.png)

That makes sense, but I think we would want to make sure the dependencies for `markdown-cli` are complete so that users do not have to install additional packages (e.g., `jsome` in this case), by hand.

**Comment by KL13NT** [comment]
> Could you clarify this comment? If you are having trouble installing the `markdown-transform` package locally, we would certainly welcome a new issue on that.

I was referring to building the package using Webpack since it has some configuration in those folders. 

And yes, if the package is moved from `devDependencies` to `dependencies` then the issue would probably be solved. Should I PR?

**Comment by irmerk** [comment]
Closing due to #40.
