### ISSUE TITLE
Markus Transform to PDF does not render images embedded within unordered list.

### ISSUE THREAD

**Issue by martinhalford** [accordproject/markdown-transform#298]
**Describe the bug**

Markus PDF transform renders embedded images okay *except* when these images are embedded in an unordered list.

Consider the following TemplateMark syntax.
```
**SIGNATURES**
-  **Jack Walnut**
   -  OTP Sent To: jackwalnut@gmail.com
   -  OTP Sent At: 17-Dec-2020 15:10:35
   -  OTP Verified At: 17-Dec-2020 15:11:23
   -  Signing Completed At: 17-Dec-2020 15:00:00
   -  ![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA/EAAAGaCAIAAADID1RyAAAAAXNSR0IArs4c6QAAAGxlWElmTU0AKgAAAAgABAEaAAUAAAAB ......  kSuQmCC)
-  **Betty Beetroot**
   -  OTP Sent To: bettybeetroot@gmail.com
   -  OTP Sent At: 17-Dec-2020 15:10:35
   -  OTP Verified At: 17-Dec-2020 15:11:23
   -  Signing Completed At: 17-Dec-2020 15:00:00
   -  ![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA/QAAAGgCAMAAAAze9yYAAAA+VBMVEX///8AgALi3ND8/fwJgQX0+fQNgwkVhBDv9u74+/gZh .... 6iU5ErkJggg==)
```
This markdown renders in Templatemark dingus as follows:

![image](https://user-images.githubusercontent.com/970336/90972130-c351f600-e559-11ea-845d-b82d150820f5.png)

However, after executing `$ markus transform --input ./text/sample.md --to pdf --output ./text/sample.pdf` the PDF is rendered as:

![image](https://user-images.githubusercontent.com/970336/90972162-0b711880-e55a-11ea-936f-7300c7958131.png)

**Describe the solution you'd like**
Would be great if Markus PDF transform could handle images embedded in unordered lists too.

**Additional context**
```
$ markus --version
0.12.6
$ cicero --version
0.21.3
```

**Additional context**
See the attached sample files.

[sample.md.txt](https://github.com/accordproject/markdown-transform/files/5113575/sample.md.txt)

[sample.pdf](https://github.com/accordproject/markdown-transform/files/5113576/sample.pdf)

**Comment by jeromesimeon** [comment]
Fixed in #307
