### ISSUE TITLE
YY format in dates does not parse properly

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#332]
To reproduce. e.g., here in template studio:
<img width="1420" alt="Screenshot 2020-09-17 at 3 01 32 PM" src="https://user-images.githubusercontent.com/670099/93515520-b7f2b000-f8f6-11ea-88b4-ae4ca5358d60.png">

For the grammar:
<img width="1070" alt="Screenshot 2020-09-17 at 3 01 41 PM" src="https://user-images.githubusercontent.com/670099/93515527-bcb76400-f8f6-11ea-922c-6023b3076c50.png">

**Comment by jeromesimeon** [comment]
^^^ @DianaLease

**Comment by jeromesimeon** [comment]
much easier. it's only about removing it from the documentation as well. Leaving this issue open until the new documentation is out.

**Comment by DianaLease** [comment]
Sounds reasonable to me!

**Comment by jeromesimeon** [comment]
`YY` is not longer a supported format (see https://docs.accordproject.org/docs/markup-templatemark.html#datetime-variables)
