### ISSUE TITLE
Variable values are quoted

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-transform#34]
**Describe the bug**

When variables are generated the value includes an extra quote (escaped as %22).

```
<variable id="shipper" value="%22Party%20A%22"/>
```

**Comment by jeromesimeon** [comment]
Two comments:
- Is that a problem? To be consistent with parsing in Cicero, one would have to re-create the quotes for variables of type `String` but not for others, which is somewhat intricate.
- Isn't this behaviour coming out of Cicero, not markdown-transform? (Also see https://github.com/accordproject/cicero/issues/305)

**Comment by dselman** [comment]
Closing as 'by design".
