### ISSUE TITLE
Cannot format {{this}} within {{#optional}} block

### ISSUE THREAD

**Issue by martinhalford** [accordproject/markdown-transform#345]
Consider the following grammar:
```
Payment due by {{dueDate as "DD MMMM YYYY"}}
{{#optional dueDate}}Payment due by {{this as "DD MMMM YYYY"}}{{/optional}}
```
where `dueDate` is defined in the model as:
```
o DateTime dueDate optional
```
The draft output is:
```
Payment due by 17 December 2020
Payment due by 12/17/2020
```

It looks like the formatting for the DateTime variable was applied for the first line in the grammar but ignored for the second line in the grammar where the variable is referenced via `{{this}}`.

It would be nice if optional variables could be formatted using the above syntax.

To reproduce, execute `draft` command on attached template using the included `data.json` file:
```
cicero draft --template . --data ./data.json --output ./text/sample.md
```

[empty-contract.zip](https://github.com/accordproject/markdown-transform/files/5421544/empty-contract.zip)

**Comment by martinhalford** [comment]
Bonus issue:

For an `optional` DateTime variable defined as:

```
  o DateTime loanApproved optional
```
...when attempting to use the `format` command, like so:

```
{{%
    "Loan Approval Date: " ++ format(loanApproved, "DD MMMM YYYY")
%}}
``` 
...then following error is thrown:
```
Function `org.accordproject.time.format' expected argument `x' to be of type `DateTime' but was given argument of type `DateTime?'.
```

**Comment by jeromesimeon** [comment]
> Bonus issue:
> 
> For an `optional` DateTime variable defined as:
> 
> ```
>   o DateTime loanApproved optional
> ```
> 
> ...when attempting to use the `format` command, like so:
> 
> ```
> {{%
>     "Loan Approval Date: " ++ format(loanApproved, "DD MMMM YYYY")
> %}}
> ```
> 
> ...then following error is thrown:
> 
> ```
> Function `org.accordproject.time.format' expected argument `x' to be of type `DateTime' but was given argument of type `DateTime?'.
> ```

That one doesn't look like an issue, but rather like a proper type error?
