### ISSUE TITLE
Migrate CI/CD to GitHub Actions

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/markdown-transform#364]
As described in accordproject/technical-steering-committee#4

Please follow the conventions in accordproject/concerto#236

   - [x] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [x] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [x] Remove `.travis.yml` and `.travis` directories in repo
   - [x] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [x] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [x] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [x] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number (for AP maintainers: do a GitHub release)
   - [x] Update GitHub "Branch protection rules" to point to the new workflows

**Comment by Rupesh-2003** [comment]
@mttrbrts  I would like to work on this issue

**Comment by mttrbrts** [comment]
My apologies @Rupesh-2003, it seems that @jeromesimeon was pretty fast on this one!
https://github.com/accordproject/markdown-transform/pull/365

**Comment by jeromesimeon** [comment]
@Rupesh-2003 it was already done (mostly) so I only had to update with the latest versions of the script from Concerto. Thanks for offering to help!
