### ISSUE TITLE
Addition of OOXML transformers in the transformation graph in README

### ISSUE THREAD

**Issue by algomaster99** [accordproject/markdown-transform#416]
# Feature Request 🛍️

The [transformation graph](https://github.com/accordproject/markdown-transform/blob/master/packages/markdown-transform/transformations.png) should be updated in the `algo-ooxml` branch with the transformers @K-Kumar-01 is working on.

## Use Case

Broadcasts new features of `markus`.

## Possible Solution

Not sure. Probably have to start by looking at [architecture.puml](https://github.com/accordproject/markdown-transform/blob/master/architecture.puml).

**Comment by dselman** [comment]
See the README for instructions on how to regenerate architecture.puml:
https://github.com/accordproject/markdown-transform/tree/master/packages/markdown-transform

**Comment by algomaster99** [comment]
Oh, I forgot to close this issue. @K-Kumar-01 has resolved this in the [algo-ooxml](https://github.com/accordproject/markdown-transform/tree/algoo-ooxml) branch.
