### ISSUE TITLE
[Build] Failing builds due to network timeouts on model loading

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/markdown-transform#422]
# Bug Report 🐛

Currently the build fails many times when a PR is made. A re-run is required many a times for this to pass successfully. The failure is due to [this line](https://github.com/accordproject/markdown-transform/blob/f861c6e99fb2fc1cee79e2f0ee8f09389801c8c1/packages/markdown-template/test/TemplateMarkTransformer.js#L174). 
It involves fetching model but since azure(where the models are hosted) is inconsistent, we face the error.

## Expected Behavior
The build shoud pass.

## Current Behavior
The build fails,

## Possible Solution

Passing an `offline:true` flag to options will ensure the pass.

## Steps to Reproduce

1. Make a PR.
2. The build might fail with the error that it was not able to download the model.

### Desktop
 - OS: Windows, Ubuntu
 - Browser: Chrome

## Detailed Description

Passing `offline:true` will make the build pass.

**Comment by algomaster99** [comment]
@dselman @K-Kumar-01 The change is required for [more test cases](https://github.com/accordproject/markdown-transform/runs/2971814927#step:6:17180) than expected. You can see the latest build on `master` is failing.

**Comment by K-Kumar-01** [comment]
@algomaster99 
I think we would need to pass the `offline: true` option in all the instances where `loadModelManger` is used.

**Comment by algomaster99** [comment]
Right

**Comment by K-Kumar-01** [comment]
@dselman 
`const modelManager = await ModelLoader.loadModelManager([modelFilePath]);`
Here, the third argument is the options one.
Could you tell about second argument.

I want to understand how to pass the third argument without passing the second argument/ passing the appropriate second argument. 
Thanks in advance:)

**Comment by jeromesimeon** [comment]
There _is_ an issue!! @K-Kumar-01 

I still see sometimes failing tests in markdown-cli and markdown-transform but the fix in #445 should already help. I'll report when I'm done with the other packages.
