### ISSUE TITLE
Update of js-dom dependency from 15.2.1 to 16.4.0

### ISSUE THREAD

**Issue by tbrooke** [accordproject/markdown-transform#443]
I am trying to use shadow-cljs - a clojurescript compiler for clojurescript javascript interop - It compilesto javascript using  the Google closure compiler 

I get an error related to js-dom

```
 --- node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:12
constructor is missing a call to super()
```
I checked and found that it was in markdown-html where it uses version 15.2.1 I checked and the current version 16.4.0 works with shadow-cljs.

The only place I found js-dom was below:

https://github.com/accordproject/markdown-transform/blob/579f162b84ae07791cd5f28fcc152372069cb732/packages/markdown-html/package.json#L86

**Comment by jeromesimeon** [comment]
Fixed in #446
