### ISSUE TITLE
Whitespace are wrongly decoded when transforming pdf to html

### ISSUE THREAD

**Issue by martinratinaud** [accordproject/markdown-transform#502]
# Bug Report 🐛

Transform of this specific pdf file https://www.decathlon.fr/static/2019/LP/services/global-services/V21/assets/cgv.pdf leads to text with missing whitespaces.

## Expected Behavior

Launching `markus transform --input cgv.pdf --from pdf --to markdown | head -n 5` should give

```
1

CONDITIONS GÉNÉRALES DE VENTE www.decathlon.fr
```

## Current Behavior
It gives the following content with missing whitespace

```
1

CONDITIONSGÉNÉRALESDEVENTEwww.decathlon.fr
```

## Steps to Reproduce
```
wget https://www.decathlon.fr/static/2019/LP/services/global-services/V21/assets/cgv.pdf
markus transform --input cgv.pdf --from pdf --to markdown
```

## Context (Environment)
I'm working on the [Open Terms Archive](https://opentermsarchive.org/) and we use this Accord Project to transform digital services documents into markdown in order to track changes overtime.

### Desktop
- OS: macOS
- NodeJs
- Version: v16.13.1 or v14.19.1

## Detailed Description

After some investigation, the problem seems to be when transforming from `pdf` to `html`.

```
markus transform --input cgv.pdf --from pdf --to html | head -n 6
```
already gives 
```
<html>
<body>
<div class="document">
<p>1</p>
<p>CONDITIONSGÉNÉRALESDEVENTEwww.decathlon.fr</p>
```

Using an online pdf to html converter seems to be working fine. I tried this one https://pdf.online/convert-pdf-to-html and got proper white spaces

Thanks

**Comment by dselman** [comment]
This appears to be a limitation in the version of [pdf.js](https://github.com/mozilla/pdf.js/) we are using to convert from PDF to structured text. This PDF file is essentially a set of binary streams, where each stream contains a set of x,z positions for individual characters. I am investigating if we there are some pdf.js configuration options that can provide better results...

**Comment by dselman** [comment]
Thanks for the report. You should be able to test this using the `unstable` version of `markdown-cli` until the next release is created.

**Comment by martinratinaud** [comment]
Works very well, thank you so much for the fast resolution
