### ISSUE TITLE
Pdf file transform in markdown leads to almost empty file

### ISSUE THREAD

**Issue by martinratinaud** [accordproject/markdown-transform#509]
# Bug Report 🐛

Transform of this specific pdf file https://yoojo.fr/jobber-terms-fr.pdf leads to weird text transformation.

## Steps to Reproduce

Launch
```
wget https://yoojo.fr/jobber-terms-fr.pdf -O jobber.pdf
markus transform --input jobber.pdf --from pdf --to markdown | head -n 15
```

## Current Behavior
```
Conditions Générales Jobeurs France 07-06-2021 1

Conditions Générales Jobeurs France 07-06-2021 2



•



•
```
This does not correspond to the content of the file

## Expected behaviour

Get as close to possible to content of file

## Possible solution

Even if I open the file with preview (on Mac), I can't copy the content of the file

### Desktop
 - OS: MacOS
 - Browser: command line
 - Version: markus 0.15.2

**Comment by dselman** [comment]
That's one strange PDF! In Safari when I open the PDF in the browser and select a paragraph and copy to the clipboard I also get empty text when I paste.

**Comment by martinratinaud** [comment]
Indeed, I will try to ask them on twitter why this pdf is like this

**Comment by martinratinaud** [comment]
Well I think that this PDF is intended to not be converted to text so I close this.

Thanks again for your support
