### ISSUE TITLE
CiceroMark -> PDF transformation

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-transform#51]
Implement a transformation (similar to the markdown-html HtmlTransformer) that generates a PDF document from a CiceroMark DOM.

**Describe the solution you'd like**
Implement a visitor using the https://pdfkit.org library, generating paragraphs and formatted text.

**Describe alternatives you've considered**
Tried to fine a lightweight HTML -> PDF library (pure JS) but come up empty.

**Additional context**
Something small, fast and lightweight that is 100% JS. A bonus would be the ability to customise look and feel etc.

**Comment by peterhunn** [comment]
Could https://github.com/MrRio/jsPDF (docs: http://raw.githack.com/MrRio/jsPDF/master/docs/) be an option?

**Comment by dagolinuxoid** [comment]
@peterhunn it's a pretty cool pdf generator.

**Comment by devcer** [comment]
Hey, I would like to take this up. Can you help me get started with this?

**Comment by irmerk** [comment]
@devcer I believe @dselman would be the best to give you a bit of guidance on this one.

**Comment by dselman** [comment]
Both `pdfkit` and `jsPDF` look like active projects in widespread use, and both MIT licensed. I don't have a strong preference for one or the other -- as long as they work in a Node.js environment. Having both Node.js and webpage usage would be even better.

I suggest playing with the API and looking at the output and performance and posting back finding here.

**Comment by irmerk** [comment]
@devcer any progress on this?

**Comment by dselman** [comment]
Another one: https://www.npmjs.com/package/markdown-pdf

**Comment by Anubhavshakya** [comment]
@irmerk Can I work on this issue ?

**Comment by dselman** [comment]
https://github.com/bpampuch/pdfmake

Takes a declarative approach, which could make this really easy. We just have to transform the CiceroMark DOM into the JSON used by pdfmake.

**Comment by dselman** [comment]
Implemented by https://github.com/accordproject/markdown-transform/pull/243
