### ISSUE TITLE
Variable values are URI encoded in Slate DOM

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-transform#55]
The values of variables are URI encoded in the Slate DOM.

**Comment by jeromesimeon** [comment]
> The values of variables are URI encoded in the Slate DOM.

They are also URI encoded in the Cicero DOM, I don't see a good reason for that since the URI encoding is only relevant when those are represented as CommonMark `HtmlInline` blocks.

**Comment by dselman** [comment]
Closing as fixed.
