### ISSUE TITLE
add image

### ISSUE THREAD

**Issue by anandprabhakar0507** [accordproject/markdown-transform#63]
Hacktoberfest-
![download](https://user-images.githubusercontent.com/34664521/66430059-2ed8b680-e9ce-11e9-8f2e-c5d3baab1673.png)
add image for clone or fork 
![](https://i.ibb.co/XL1d3st/download.png)
[or view here](https://i.ibb.co/XL1d3st/download.png)

**Comment by irmerk** [comment]
I don't think these additions are necessary.
