### ISSUE TITLE
Method for retrieving full non-variable clause text from a clause node

### ISSUE THREAD

**Issue by DianaLease** [accordproject/markdown-transform#86]
**Is your feature request related to a problem? Please describe.**
Because the `clauseText` attribute will be removed from the clause nodes in the concerto AST, I cannot easily obtain the full text of a clause without variable syntax from the markdown string for a contract.

**Describe the solution you'd like**
Method for retrieving non-variable text from a concerto AST clause node. I believe this method would be part of the cicero mark transformer, but not positive.

**Additional context**
My use case: I have markdown that includes clauses with variable syntax, and I want to get the clauses and their non-variable text. Once the `clauseText` attribute is removed from the clause code in the concerto AST, I will need to do this hacky code (which I am trying to avoid):
```
  function getClausesFromMarkdown(markdown) {
    const commonMarkTransformer = new CommonMarkTransformer({ tagInfo: true });
    const ciceroMarkTransformer = new CiceroMarkTransformer();
    let concertoAst = commonMarkTransformer.fromMarkdown(markdown, 'json');
    concertoAst = ciceroMarkTransformer.fromCommonMark(concertoAst, 'json');
    const clauseNodes = concertoAst.nodes.filter(({ $class }) => $class === 'org.accordproject.ciceromark.Clause');
    return clauseNodes.map((node) => {
      const {
        clauseid, src, clauseText, ...transformedNode
      } = node;
      return ({
        ...node,
        clauseText: ciceroMarkTransformer.toMarkdown({ ...transformedNode, $class: 'org.accordproject.commonmark.Paragraph' }, { wrapVariables: false })
      });
    });
  }
```

**Comment by jeromesimeon** [comment]
@DianaLease I don't think I was thinking straight last night, and after going down a rabbit's hole for a bit, I realised there is an easy way to get the clause text already:

Instead of going directly from CiceroMark DOM to CommonMark text with:
```
ciceroMarkTransformer.toMarkdown(clauseNode)
```
Instead generate the CommonMark DOM *then* get the text:
```
ciceroMarkTransformer.toCommonMark(clauseNode).text;
```

You should be able to test that. Let me know if it works, and I will then remove the `clauseText` field from the Clause node.

**Comment by DianaLease** [comment]
Recapping an outside convo here -
The above proposed solution produces the text but with the variable syntax still present. It would be useful to have a way to pass `{ wrapVariables: false }` as an argument to the `toCommonMark` method, similar to how it can currently be passed to the `toMarkdown` method.

**Comment by jeromesimeon** [comment]
> @DianaLease I don't think I was thinking straight last night, and after going down a rabbit's hole for a bit, I realised there is an easy way to get the clause text already:
> 
> Instead of going directly from CiceroMark DOM to CommonMark text with:
> 
> ```
> ciceroMarkTransformer.toMarkdown(clauseNode)
> ```
> 
> Instead generate the CommonMark DOM _then_ get the text:
> 
> ```
> ciceroMarkTransformer.toCommonMark(clauseNode).text;
> ```
> 
> You should be able to test that. Let me know if it works, and I will then remove the `clauseText` field from the Clause node.

Adding the call to clarify what to do to get the text _without_ variable tags:

```
ciceroMarkTransformer.toCommonMark(clauseNode, 'json', { wrapVariables: false }).text;
```

**Comment by jeromesimeon** [comment]
I have added a method to encapsulate the clause text extraction:

```
ciceroMarkTransformer.getClauseText(clauseNode, { wrapVariables: BOOLEAN })
```

This will:
1. regenerate the clause text (with or without wrapped variables)
2. remove single trailing new line due to code blocks encodings in CommonMark
3. raise an exception for non-Clause nodes

**Comment by jeromesimeon** [comment]
`clauseText` field from CiceroMark has been removed. Will ship with release `0.6.0`

@DianaLease Can we consider this issue resolved?

**Comment by DianaLease** [comment]
> @DianaLease Can we consider this issue resolved?

Yes, works for me!
